name: Performance Budget

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  perf-budget:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Run Performance Budget
        run: |
          node scripts/perfBudget.mjs PERF_OUTPUT_JSON=1 PERF_WARN_ONLY=1
      - name: Upload perf report artifact
        uses: actions/upload-artifact@v4
        with:
          name: perf-budget-report
          path: .next/perf-budget.json
        if: always()
